### ISSUE TITLE
pragmatic segmenter not installing

### ISSUE THREAD

**Issue by sevilaybayatli** [diasks2/pragmatic_segmenter#66]
Hello,

I have been using pragmatic segmenter for two years as below:
sudo apt-get install ruby-full
gem install pragmatic_segmenter

Successfully installed pragmatic_segmenter-0.3.22
Parsing documentation for pragmatic_segmenter-0.3.22
Done installing documentation for pragmatic_segmenter after 0 seconds
1 gem installed

And here my sentenceTokenizer.rb
require 'pragmatic_segmenter'

if (ARGV.length < 3)
  puts "\nUsage : ruby2.5 sentenceTokenizer.rb 639-1ISOlangCode textFilePath sentencesFilePath"
  exit
end

File.open(ARGV[1]).each do |line1|
	line1.delete! ('\\\(\)\[\]\{\}\<\>\|\$\/\'\"')
  ps = PragmaticSegmenter::Segmenter.new(text: line1, language: ARGV[0], doc_type: 'txt')
  sentences = ps.segment
    
  File.open(ARGV[2], "a") do |line2|
      sentences.each { |sentence| line2.puts sentence }  
  end
end

but the problem when I run it now 

Traceback (most recent call last):
	2: from sentenceTokenizer.rb:1:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- pragmatic_segmenter (LoadError)

I tried to search of pragmatic segmenter it seems no installed? Could you point me and tell me where I am doing wrong.

**Comment by alextsui05** [comment]
I responded here before I saw this issue, please check it 👉  https://github.com/diasks2/pragmatic_segmenter/issues/69#issuecomment-763074625

**Comment by diasks2** [comment]
Is this solved with the newest version: https://github.com/diasks2/pragmatic_segmenter/pull/68 ?
